// added a tracker list to the reflecting activity to keep track of the used questions.
// if the index of a question is generated by the random number generator, it is checked against the tracker. 
// a new index is generated if the previous one is already in the list

using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello Develop04 World!");
        string option;

        option = "";// initializing the option to select an activity 
        
        do
        {
            //display a welcoming message and the menu
            Console.WriteLine("Welcome to the mindfulness program. please type the number of the activity that your want, or type 4 to exit.");
            Console.WriteLine("1. Breathing Activity");
            Console.WriteLine("2. Reflecting Activity");
            Console.WriteLine("3. Listing Activity");
            Console.WriteLine("4. Quit");
            Console.Write("Type your selection and press enter. : ");
            option = Console.ReadLine(); //wait for user input

            // if loop to process user input and run approppriate activity.
            if (option == "1")
            {
                BreathingActivity breathingActivity = new BreathingActivity();
                breathingActivity.Run();
            }

            else if (option == "2")
            {
                ReflectingActivity reflectingActivity = new ReflectingActivity();
                reflectingActivity.Run();
            }

            else if (option == "3")
            {
                ListingActivity listingActivity = new ListingActivity();
                listingActivity.Run();
            }

            else if (option == "4")// to end the program
            {
                Console.Write("The program will end in: ");
                Activity spin = new Activity();
                spin.ShowCountDown(2);
            }
            else //error message incase od invalid input.
            {
                Console.Write("Invalid selection. Try again in: ");
                Activity spin = new Activity();
                spin.ShowCountDown(2);
                Console.Clear();
            }

        }
        while (option != "4");
    }
}